ALTER TABLE  `<DB_PREFIX>countries` CHANGE  `abbrv`  `abbrv` VARCHAR( 2 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;

INSERT INTO `<DB_PREFIX>modules` (`id`, `name`, `name_const`, `description_const`, `icon_file`, `module_tables`, `dependent_modules`, `settings_page`, `settings_const`, `settings_access_by`, `management_page`, `management_const`, `management_access_by`, `is_installed`, `is_system`, `priority_order`) VALUES (NULL, 'featured_content', '_FEATURED_CONTENT', '_MD_FEATURED_CONTENT', 'featured.png', 'featured_content', '', '', '', 'owner,mainadmin', 'mod_featured_content_management', '_FEATURED_CONTENT_MANAGEMENT', 'owner,mainadmin', '1', '0', '11');
INSERT INTO `<DB_PREFIX>modules` (`id`, `name`, `name_const`, `description_const`, `icon_file`, `module_tables`, `dependent_modules`, `settings_page`, `settings_const`, `settings_access_by`, `management_page`, `management_const`, `management_access_by`, `is_installed`, `is_system`, `priority_order`) VALUES (NULL, 'testimonials', '_TESTIMONIALS', '_MD_TESTIMONIALS', 'testimonials.png', 'testimonials', '', 'mod_testimonials_settings', '_TESTIMONIALS_SETTINGS', 'owner,mainadmin', 'mod_testimonials_management', '_TESTIMONIALS_MANAGEMENT', 'owner,mainadmin', 1, 0, 9);
ALTER TABLE `<DB_PREFIX>modules` ADD  `show_on_dashboard` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT  '0' AFTER  `is_system`;

INSERT INTO `<DB_PREFIX>modules_settings` (`id`, `module_name`, `settings_key`, `settings_value`, `settings_name`, `settings_description_const`, `key_display_type`, `key_is_required`, `key_display_source`) VALUES (NULL, 'testimonials', 'key', '{module:testimonials}', 'Testimonials Key', '_MS_TESTIMONIALS_KEY', 'enum', 1, '{module:testimonials}');
INSERT INTO `<DB_PREFIX>modules_settings` (`id`, `module_name`, `settings_key`, `settings_value`, `settings_name`, `settings_description_const`, `key_display_type`, `key_is_required`, `key_display_source`) VALUES (NULL, 'banners', 'slideshow_caption_html', 'yes', 'HTML in Slideshow Caption', '_MS_BANNERS_CAPTION_HTML', 'yes/no', '1', '');
INSERT INTO `<DB_PREFIX>modules_settings` (`id`, `module_name`, `settings_key`, `settings_value`, `settings_name`, `settings_description_const`, `key_display_type`, `key_is_required`, `key_display_source`) VALUES (NULL, 'gallery', 'show_items_numeration_in_album', 'yes', 'Show Items Numeration in Album', '_MS_ALBUM_ITEMS_NUMERATION', 'yes/no', 1, '');

ALTER TABLE  `<DB_PREFIX>accounts` CHANGE  `last_login`  `date_lastlogin` DATETIME NOT NULL DEFAULT  '0000-00-00 00:00:00';

ALTER TABLE  `<DB_PREFIX>languages` ADD  `lc_time_name` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT  'en_US' AFTER  `abbreviation`;

ALTER TABLE  `<DB_PREFIX>settings` ADD  `mailer_wysiwyg_type` ENUM(  'none',  'tinymce' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT  'none' AFTER  `mailer_type` ;
ALTER TABLE  `<DB_PREFIX>settings` ADD  `smtp_secure` ENUM(  'ssl',  'no' ) NOT NULL DEFAULT  'ssl' AFTER  `mailer_wysiwyg_type` ;
UPDATE `<DB_PREFIX>settings` SET `wysiwyg_type` ='tinymce';
ALTER TABLE  `<DB_PREFIX>settings` CHANGE  `wysiwyg_type`  `wysiwyg_type` ENUM(  'none',  'tinymce' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT  'tinymce';
ALTER TABLE  `<DB_PREFIX>settings` ADD  `week_start_day` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT  '1' AFTER  `time_zone`;
ALTER TABLE  `<DB_PREFIX>settings` ADD  `ssl_mode` TINYINT( 1 ) NOT NULL DEFAULT  '0' COMMENT  '0 - no, 1 - entire site, 2 - admin, 3 - user' AFTER  `template`;


ALTER TABLE  `<DB_PREFIX>menus` CHANGE  `menu_placement`  `menu_placement` ENUM(  '',  'left',  'top',  'right',  'bottom',  'hidden' ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;

DROP TABLE IF EXISTS `<DB_PREFIX>featured_content`;
CREATE TABLE IF NOT EXISTS `<DB_PREFIX>featured_content` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content_header` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `content_text` text COLLATE utf8_unicode_ci NOT NULL,
  `content_link` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `content_icon` varchar(125) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;


DROP TABLE IF EXISTS `<DB_PREFIX>testimonials`;
CREATE TABLE IF NOT EXISTS `<DB_PREFIX>testimonials` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `author_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `author_country` varchar(2) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `author_city` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `author_email` varchar(70) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `testimonial_text` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `priority_order` smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 ;


INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_SERVER_LOCALE', 'Server Locale'), (NULL, 'es', '_SERVER_LOCALE', 'servidor local'), (NULL, 'de', '_SERVER_LOCALE', 'Server locale');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_UNDEFINED', 'undefined'), (NULL, 'es', '_UNDEFINED', 'indefinido'), (NULL, 'de', '_UNDEFINED', 'undefiniert');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_SMTP_SECURE', 'SMTP Secure'), (NULL, 'es', '_SMTP_SECURE', 'Secure SMTP'), (NULL, 'de', '_SMTP_SECURE', 'SMTP Sichere');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_EMAIL_TEMPLATES_EDITOR', 'Email Templates Editor'), (NULL, 'es', '_EMAIL_TEMPLATES_EDITOR', 'Plantillas de correo electrónico del editor'), (NULL, 'de', '_EMAIL_TEMPLATES_EDITOR', 'E-Mail-Editor');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_DASHBOARD', 'Dashboard'), (NULL, 'es', '_DASHBOARD', 'Salpicadero'), (NULL, 'de', '_DASHBOARD', 'Armaturenbrett');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_INVALID_FILE_SIZE', 'Invalid file size: _FILE_SIZE_ (max. allowed: _MAX_ALLOWED_)'), (NULL, 'es', '_INVALID_FILE_SIZE', 'Tamaño de archivo no válido: _FILE_SIZE_ (máximo permitido: _MAX_ALLOWED_)'), (NULL, 'de', '_INVALID_FILE_SIZE', 'Ungültige Dateigröße: _FILE_SIZE_ (max. erlaubt: _MAX_ALLOWED_)');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_GENERATE', 'Generate'), (NULL, 'es', '_GENERATE', 'Generar'), (NULL, 'de', '_GENERATE', 'Erzeugen');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_USE_THIS_PASSWORD', 'Use this password'), (NULL, 'es', '_USE_THIS_PASSWORD', 'Verwenden Sie dieses Kennwort'), (NULL, 'de', '_USE_THIS_PASSWORD', 'Utilice esta contraseña'); 
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_FEATURED_CONTENT', 'Featured Content'), (NULL, 'es', '_FEATURED_CONTENT', 'Contenido Destacado'), (NULL, 'de', '_FEATURED_CONTENT', 'Featured Content');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_FEATURED_CONTENT_MANAGEMENT', 'Featured Content Management'), (NULL, 'es', '_FEATURED_CONTENT_MANAGEMENT', 'Gestión de contenidos destacados'), (NULL, 'de', '_FEATURED_CONTENT_MANAGEMENT', 'Vorgestellten Content Management');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_MD_FEATURED_CONTENT', 'This module allows to create and manage featured content that will be shown in special block on the Front-End of the site. '), (NULL, 'es', '_MD_FEATURED_CONTENT', 'Este módulo permite crear y gestionar contenido destacado que se muestra en el bloque especial en el front-end del sitio.'), (NULL, 'de', '_MD_FEATURED_CONTENT', 'Dieses Modul ermöglicht die Erstellung und Verwaltung vorgestellten Inhalte, die in speziellen Block auf dem Front-End der Website angezeigt werden.');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_ADMIN_FOLDER_CREATION_ERROR', 'Failed to create folder for this author in <b>images/upload/</b> directory. For stable work of the script please create this folder manually.'), (NULL, 'es', '_ADMIN_FOLDER_CREATION_ERROR', 'No se pudo crear la carpeta para este autor en <b>images/upload/</b> directorio. Para el trabajo estable de la secuencia de comandos por favor crear esta carpeta de forma manual.'), (NULL, 'de', '_ADMIN_FOLDER_CREATION_ERROR', 'Fehler beim Ordner zu diesem Autor in <b>images/upload/</b> Verzeichnis. Für eine stabile Arbeit des Skripts erstellen Sie bitte diesen Ordner manuell.');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_VIEW_ALL', 'View All'), (NULL, 'es', '_VIEW_ALL', 'Ver todos'), (NULL, 'de', '_VIEW_ALL', 'Alle anzeigen');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_OWNER', 'Owner'), (NULL, 'es', '_OWNER', 'Propietario'), (NULL, 'de', '_OWNER', 'Eigentümer');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'de', '_MD_TESTIMONIALS', 'Die Testimonials Modul ermöglicht den Administrator der Website zum Hinzufügen / Bearbeiten Aussagen der Nutzer, verwalten Sie sie und zeigen auf dem Frontend MicroCMS.'), (NULL, 'en', '_MD_TESTIMONIALS', 'The Testimonials Module allows the administrator of the site to add/edit user testimonials, manage them and show on the MicroCMS frontend.'), (NULL, 'es', '_MD_TESTIMONIALS', 'El Módulo Testimonios permite al administrador del sitio para añadir / editar testimonios de usuarios, gestionar y mostrar en la interfaz MicroCMS.');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'de', '_MS_TESTIMONIALS_KEY', 'Das Schlüsselwort, das mit einer Liste von Aussagen der Nutzer (kopieren und fügen Sie ihn auf der Seite) ersetzt werden'), (NULL, 'en', '_MS_TESTIMONIALS_KEY', 'The keyword that will be replaced with a list of user testimonials (copy and paste it into the page)'), (NULL, 'es', '_MS_TESTIMONIALS_KEY', 'La palabra clave que se reemplazará con una lista de testimonios de usuarios (copie y péguelo en la página)');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'de', '_TESTIMONIALS', 'Zeugnisse'), (NULL, 'en', '_TESTIMONIALS', 'Testimonials'), (NULL, 'es', '_TESTIMONIALS', 'Testimonios');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'de', '_TESTIMONIALS_MANAGEMENT', 'Management von Testimonials'), (NULL, 'en', '_TESTIMONIALS_MANAGEMENT', 'Testimonials Management'), (NULL, 'es', '_TESTIMONIALS_MANAGEMENT', 'Gestión de los testimonios');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'de', '_TESTIMONIALS_SETTINGS', 'Zeugnisse Einstellungen'), (NULL, 'en', '_TESTIMONIALS_SETTINGS', 'Testimonials Settings'), (NULL, 'es', '_TESTIMONIALS_SETTINGS', 'Configuración de testimonios'); 
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_MS_BANNERS_CAPTION_HTML', 'Specifies whether to allow using of HTML in slideshow captions or not'), (NULL, 'es', '_MS_BANNERS_CAPTION_HTML', 'Especifica si se debe permitir el uso de HTML en los textos de presentación de diapositivas o no'), (NULL, 'de', '_MS_BANNERS_CAPTION_HTML', 'Gibt an, ob mit Hilfe von HTML-Diashow in Bildunterschriften oder nicht');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_MS_ALBUM_ITEMS_NUMERATION', 'Specifies whether to show items numeration in albums'), (NULL, 'es', '_MS_ALBUM_ITEMS_NUMERATION', 'Especifica si se deben mostrar los elementos de numeración en álbumes'), (NULL, 'de', '_MS_ALBUM_ITEMS_NUMERATION', 'Gibt an, ob Elemente Nummerierung in Alben zeigen');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_DISABLED', 'disabled'), (NULL, 'es', '_DISABLED', 'discapacitado'), (NULL, 'de', '_DISABLED', 'behindert');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_MENUS_DISABLED_ALERT', 'Take in account that some menus may be disabled for this template.'), (NULL, 'es', '_MENUS_DISABLED_ALERT', 'Tome en cuenta que algunos menús pueden ser deshabilitados para esta plantilla.'), (NULL, 'de', '_MENUS_DISABLED_ALERT', 'Nehmen Sie in Rechnung, dass einige Menüs für diese Vorlage kann deaktiviert werden.');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_HIDDEN', 'Hidden'), (NULL, 'es', '_HIDDEN', 'Oculto'), (NULL, 'de', '_HIDDEN', 'Versteckt');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text` )VALUES (NULL, 'en', '_SUNDAY', 'Sunday'), (NULL, 'es', '_SUNDAY', 'domingo'), (NULL, 'de', '_SUNDAY', 'Sonntag');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_MONDAY', 'Monday'), (NULL, 'es', '_MONDAY', 'dlunes'), (NULL, 'de', '_MONDAY', 'Montag');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_TUESDAY', 'Tuesday'), (NULL, 'es', '_TUESDAY', 'martes'), (NULL, 'de', '_TUESDAY', 'Dienstag');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_WEDNESDAY', 'Wednesday'), (NULL, 'es', '_WEDNESDAY', 'miércoles'), (NULL, 'de', '_WEDNESDAY', 'Mittwoch');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_THURSDAY', 'Thursday'), (NULL, 'es', '_THURSDAY', 'jueves'), (NULL, 'de', '_THURSDAY', 'Donnerstag');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_FRIDAY', 'Friday'), (NULL, 'es', '_FRIDAY', 'viernes'), (NULL, 'de', '_FRIDAY', 'Freitag');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_SATURDAY', 'Saturday'), (NULL, 'es', '_SATURDAY', 'sábado'), (NULL, 'de', '_SATURDAY', 'Samstag');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_SET_TIME', 'Set Time'), (NULL, 'es', '_SET_TIME', 'Ajuste de la hora'), (NULL, 'de', '_SET_TIME', 'Eingestellte Zeit');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'de', '_WEEK_START_DAY', 'Woche Starttag'), (NULL, 'en', '_WEEK_START_DAY', 'Week Start Day'), (NULL, 'es', '_WEEK_START_DAY', 'Semana Día de inicio');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'de', '_INVALID_IMAGE_FILE_TYPE', 'Hochgeladene Datei ist kein gültiges Bild! Bitte geben Sie erneut.'), (NULL, 'en', '_INVALID_IMAGE_FILE_TYPE', 'Uploaded file is not a valid image! Please re-enter.'), (NULL, 'es', '_INVALID_IMAGE_FILE_TYPE', 'El archivo cargado no es una imagen válida! Por favor, vuelva a entrar.');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_SHOW_ON_DASHBOARD', 'Show on Dashboard'), (NULL, 'es', '_SHOW_ON_DASHBOARD', 'Mostrar en el Dashboard'), (NULL, 'de', '_SHOW_ON_DASHBOARD', 'Anzeigen auf Armaturenbrett');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'de', '_MENUS_AND_PAGES', 'Menüs und Seiten'), (NULL, 'en', '_MENUS_AND_PAGES', 'Menus and Pages'), (NULL, 'es', '_MENUS_AND_PAGES', 'Los menús y páginas');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_USERS_AWAITING_MODERATION_ALERT', 'There are _COUNT_ users/s awaiting your approval. Click <a href=''index.php?admin=mod_users_management''>here</a> for review.'), (NULL, 'es', '_USERS_AWAITING_MODERATION_ALERT', 'Hay _COUNT_ cliente/s en espera de su aprobación. Haga clic <a href=''index.php?admin=mod_users_management''>aquí</a> para su revisión.'), (NULL, 'de', '_USERS_AWAITING_MODERATION_ALERT', 'Es gibt _COUNT_ Kunde/n Erwartung Ihrer Zustimmung. Klicken Sie <a href=''index.php?admin=mod_users_management''>hier</a> für die Überprüfung.'), (NULL, 'fr', '_USERS_AWAITING_MODERATION_ALERT', 'Il ya _COUNT_ clients en attente de votre approbation. Cliquez <a href=''index.php?admin=mod_users_management''>ici</a> pour examen.');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_ENTIRE_SITE',  'Entire Site'), (NULL, 'es', '_ENTIRE_SITE', 'Todo el sitio web'), (NULL, 'de', '_ENTIRE_SITE', 'Die ganze Site');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_ADMINISTRATOR_ONLY',  'Administrator Only'), (NULL, 'es', '_ADMINISTRATOR_ONLY',  'Administrador con permiso de'), (NULL, 'de', '_ADMINISTRATOR_ONLY',  'Nur Administrator');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_FORCE_SSL', 'Force SSL'), (NULL, 'es', '_FORCE_SSL', 'Fuerza SSL'), (NULL, 'de', '_FORCE_SSL', 'Force-SSL');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_FORCE_SSL_ALERT', 'Force site access to always occur under SSL (https) for selected areas. You or site visitors will not be able to access selected areas under non-ssl. Note, you must have SSL enabled on your server to make this option works.'), (NULL, 'es', '_FORCE_SSL_ALERT', 'Acceso Fuerza del sitio que se produzca siempre bajo SSL (https) para las áreas seleccionadas. Usted o visitantes del sitio no será capaz de acceder a las áreas seleccionadas en virtud de que no sea SSL. Tenga en cuenta, debe tener habilitado SSL en el servidor para que esta opción funcione.'), (NULL, 'de', '_FORCE_SSL_ALERT', 'Force-Website Zugriff auf immer unter SSL (https) treten für ausgewählte Bereiche. Sie oder Website-Besucher nicht in der Lage zu ausgewählten Bereichen unter Nicht-SSL-Zugang. Beachten Sie, müssen Sie SSL-fähigen auf Ihrem Server haben, damit diese Option funktioniert.');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_USER_ONLY', 'User Only'), (NULL, 'es', '_USER_ONLY', 'Sólo usuarios'), (NULL, 'de', '_USER_ONLY',  'Nur Benutzer');
INSERT INTO `<DB_PREFIX>vocabulary` (`id`, `language_id`, `key_value`, `key_text`) VALUES (NULL, 'en', '_MODULE_CONTACT_ALERT', 'For proper work, use only on pages with blocked commenting');
